### ISSUE TITLE
Error: path not found

### ISSUE THREAD

**Issue by kirillkharunzhin** [maksimryndin/ekubo-atomic-arbitrage#2]
Hello. After changing account and private key parameters and launching cargo run I got this.
Idea is brilliant anyway.

Compiling ekubo-atomic-arbitrage v0.1.0 (C:\Starknet\ekubo-atomic-arbitrage-main\atomic-arbitrage)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 55.80s
     Running `target\debug\ekubo-atomic-arbitrage.exe`
Error: path not found

Caused by:
    path not found

Location:
    atomic-arbitrage\src/main.rs:209:5
error: process didn't exit successfully: `target\debug\ekubo-atomic-arbitrage.exe` (exit code: 1)

**Comment by maksimryndin** [comment]
Hi Kirill! Thank you! :) I haven't tested under Windows but the error and its location point to [the line 209](https://github.com/maksimryndin/ekubo-atomic-arbitrage/blob/main/atomic-arbitrage/src/main.rs#L209C5-L209C24) which means that the `.env` file is not found. `dotenvy` crate [seems](https://github.com/allan2/dotenvy/blob/master/dotenv/src/find.rs#L37) to look for `.env` files along the path of your binary current dir. So be sure that 2 conditions uphold:
1. The file is named `.env`
2. It is at some directory in the path (`C:\Starknet\ekubo-atomic-arbitrage-main`) of your binary current dir (it is the root of the repo and up)

Could you please tell me if it works for you?

**Comment by kirillkharunzhin** [comment]
I tried moving the .env to /taget/debug 
Same error. 
What do you think about using strk tokens for gas fee?

**Comment by maksimryndin** [comment]
Have you tried to put the `.env` at the root of the repository (`C:\Starknet\ekubo-atomic-arbitrage-main`)?

On STRK - on my side there is no strong preference but you should change the logic a bit:
1) You should use [transaction v3](https://docs.rs/starknet/latest/starknet/accounts/trait.Account.html#method.execute_v3) [here](https://github.com/maksimryndin/ekubo-atomic-arbitrage/blob/main/atomic-arbitrage/src/main.rs#L354C22-L354C32) and [here](https://github.com/maksimryndin/ekubo-atomic-arbitrage/blob/main/atomic-arbitrage/src/main.rs#L342)
2)  [the comparison](https://github.com/maksimryndin/ekubo-atomic-arbitrage/blob/main/atomic-arbitrage/src/main.rs#L352) of profit and fees should be adjusted as the profit is nominated in ETH

**Comment by maksimryndin** [comment]
Hey @kirillkharunzhin! I've also added the `path` cli argument to specify env file path
